name: Monitoring Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose syntax
        run: docker compose config

      - name: Build all services
        run: docker compose build

      - name: List built images
        run: docker images

      - name: Run services (detached)
        run: docker compose up -d

      - name: Wait and check running containers
        run: |
          sleep 10
          docker ps -a

      - name: Stop and clean up
        run: docker compose down
